name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  lint-format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      HUSKY: 0
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install NPM dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:ci

      - name: Format
        run: npm run format:ci
